In [1]:
import numpy as np
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : integer or real, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : integer or real
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off 

In [8]:
# Creating arrays
x = np.arange(5)
x
y = np.arange(1,6)
y
print(x/y)


[0.         0.5        0.66666667 0.75       0.8       ]


In [24]:
#Printing 1-D arrays
print("Print 1-D array")
x = np.arange(9)
print(type(x))
print(x, '\n')

print("Printing 3x3 array")
a3x3 = x.reshape(3,3)
print(a3x3, '\n')
print(2** a3x3)

print("Printing 2x3 array")
a2x3 = np.array([[0,1,2],[3,4,5]])
print(a2x3,'\n')
print(a2x3 +1)

Print 1-D array
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8] 

Printing 3x3 array
[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[  1   2   4]
 [  8  16  32]
 [ 64 128 256]]
Printing 2x3 array
[[0 1 2]
 [3 4 5]] 

[[1 2 3]
 [4 5 6]]


In [31]:
#create a 2x2 array of zeros
ex1 = np.zeros((2,2))
print(ex1)
print()

#create 2x2 array with values 9.0
ex2 = np.full((2,2),9.0)
print(ex2)
print()

#create an array of ones
ex3 = np.ones((1,2))
print(ex3)
print()

#create an array of random floats between 0 and 1
ex4 = np.random.random((2,2))
print(ex4)


[[0. 0.]
 [0. 0.]]

[[9. 9.]
 [9. 9.]]

[[1. 1.]]

[[0.12776973 0.58565238]
 [0.1121539  0.30322718]]


In [38]:
months = np.array([['Jan', 'Feb','Mar', 'Apr', 'May','Jun', 'July', 'Aug', 'Sept', 'Oct','Nov', 'Dec']])
print(months)

[['Jan' 'Feb' 'Mar' 'Apr' 'May' 'Jun' 'July' 'Aug' 'Sept' 'Oct' 'Nov'
  'Dec']]


In [37]:
#appending an array
np.append([1,2,3],[[4,5,6],[7,8,9]])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
a1 = np.array(['hello', 'world'])
a2 = np.array(['data', 'python'])
np.append(a1,a2)

array(['hello', 'world', 'data', 'python'], dtype='<U6')

In [51]:
#Indexing 1 dimensional array
print('1-D')
print(x, 'size: ', x.shape)
print(x[0], x[1], x[7])
print()

#Indexing in 2-D
print('2x3')
print(a2x3, 'size: ', a2x3.shape)
print()
print(a2x3[0], ' row1') #first row
print(a2x3[1], ' row2') #second row
print('R1 ,C3: ',a2x3[0][2]) #First row third column
print('R1 , C1:', a2x3[0][0]) #First row, first column


1-D
[0 1 2 3 4 5 6 7 8] size:  (9,)
0 1 7

2x3
[[0 1 2]
 [3 4 5]] size:  (2, 3)

[0 1 2]  row1
[3 4 5]  row2
R1 ,C3:  2
R1 , C1: 0


In [68]:
#Slice Indexing

an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)
print()
a_slice = an_array[:2]  # first 2 rows
print(a_slice)
print()
#print 2 and 3nd rows
a_slice = an_array[1:3]
print(a_slice)
print()
#print 2 rows 2cols
a_slice = an_array[:2, 1:3]
print(a_slice)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]

[[11 12 13 14]
 [21 22 23 24]]

[[21 22 23 24]
 [31 32 33 34]]

[[12 13]
 [22 23]]


In [78]:
# slicing and integer indexing
row_rank1 = an_array[1,:]
print(row_rank1, row_rank1.shape)

row_rank2 = an_array[1:2,:]
print(row_rank2, row_rank2.shape)

#columns
print()
col_rank1 = an_array[:,1]
print(col_rank1, col_rank1.shape)
print()
col_rank2= an_array[:,1:3]
print(col_rank2, col_rank2.shape)

[21 22 23 24] (4,)
[[21 22 23 24]] (1, 4)

[12 22 32] (3,)

[[12 13]
 [22 23]
 [32 33]] (3, 2)


In [92]:
#Boolean indexing
an_array = np.array([[11,12],[23,24],[25,16]])
print(an_array)
print()

#create a filter if elements meets a condition

filter = an_array>15
print(filter)

print()
print(an_array[filter])

#without filter

print(an_array[an_array >15])
print(an_array[(an_array>15) & (an_array>25)])
#even values
print(an_array[an_array %2 ==0])
print()
#changing array using a logical filter
an_array[an_array %2==0] +=100
print(an_array)

[[11 12]
 [23 24]
 [25 16]]

[[False False]
 [ True  True]
 [ True  True]]

[23 24 25 16]
[23 24 25 16]
[]
[12 24 16]

[[ 11 112]
 [ 23 124]
 [ 25 116]]


In [94]:
#Array Arithmetic

x = np.arange(4)
print('x = ',x)
print('x+5: ', x+5)
print('x-5: ', x-5)
print('x*5: ', x*2)
print('x/2: ',x/2)
print('x//2: ', x//2) #floor division


x =  [0 1 2 3]
x+5:  [5 6 7 8]
x-5:  [-5 -4 -3 -2]
x*5:  [0 2 4 6]
x/2:  [0.  0.5 1.  1.5]
x//2:  [0 0 1 1]


In [95]:
print("-x  =", -x)
print("x ** 2: ", x**2)
print("x % 2: ", x%2)


-x  = [ 0 -1 -2 -3]
x ** 2:  [0 1 4 9]
x % 2:  [0 1 0 1]


In [99]:
-(0.5*x +1) **2


array([-1.  , -2.25, -4.  , -6.25])

In [97]:
np.add(x,3)

array([3, 4, 5, 6])

In [100]:
x = np.array([-1,-2,0,1,2])
type(x)
print(x)
print(x.shape)

[-1 -2  0  1  2]
(5,)


In [101]:
#Absolute
abs(x)


array([1, 2, 0, 1, 2])

In [102]:
np.absolute(x)

array([1, 2, 0, 1, 2])

In [103]:
np.abs(x)

array([1, 2, 0, 1, 2])

In [104]:
#Trignometric
theta = np.linspace(0,np.pi,3)
theta

array([0.        , 1.57079633, 3.14159265])

In [107]:
print("theta: ", theta)
print("sin(theta):", np.sin(theta))
print("cos(theta):", np.cos(theta))
print("tan(theta):", np.tan(theta))


theta:  [0.         1.57079633 3.14159265]
sin(theta): [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta): [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta): [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [110]:
#Inverse trig functions
x = np.array([-1,0,1])
print("x:", x)
print("arcsin(x):", np.arcsin(x))
print("arccos(x):", np.arccos(x))
print("arctan(x):", np.arctan(x))

x: [-1  0  1]
arcsin(x): [-1.57079633  0.          1.57079633]
arccos(x): [3.14159265 1.57079633 0.        ]
arctan(x): [-0.78539816  0.          0.78539816]


In [112]:
#Exponentials and Logarithmic
x = [1,2,3]
print("x is ", x)
print("e^x :", np.exp(x))
print("2^x:",np.exp2(x))
print("3^x:", np.power(3,x))
      

x is  [1, 2, 3]
e^x : [ 2.71828183  7.3890561  20.08553692]
2^x: [2. 4. 8.]
3^x: [ 3  9 27]


In [113]:
x = [1,2,4,10]
print("x is :",x)
print("ln(x)", np.log(x))
print("log2(x) ", np.log2(x))
print("log10(x): ", np.log10(x))


x is : [1, 2, 4, 10]
ln(x) [0.         0.69314718 1.38629436 2.30258509]
log2(x)  [0.         1.         2.         3.32192809]
log10(x):  [0.         0.30103    0.60205999 1.        ]


In [114]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


In [115]:
# Statistical functions
# generate a random variables of 2x4
arr = 10 * np.random.randn(2,5)
print(arr)

[[ 22.41590189  20.45985497  -0.31689173  13.68228996   0.82598279]
 [  0.23508705   2.04717252  -1.27016048   0.14540085 -11.42760321]]


In [116]:
print(arr.mean())

4.679703462435734


In [117]:
print(arr.mean(axis=1))
#mean by considering each row

[11.41342758 -2.05402065]


In [118]:
print(arr.mean(axis=0))
#mean by considering each column

[11.32549447 11.25351375 -0.7935261   6.91384541 -5.30081021]


In [119]:
print(arr.sum())

46.79703462435734


In [122]:
print(np.median(arr, axis=1))

[13.68228996  0.14540085]


In [123]:
#sorting

unsorted = np.random.randn(10)
print("unsorted", unsorted)

unsorted [-0.27232247 -1.25935351  0.07336406  1.39158573  0.50497573 -1.54167276
 -1.23853319 -0.25089091 -1.28599589 -0.58735763]


In [128]:
#1 create copy and sort

print("Sorted")
sorted = np.array(unsorted)
sorted.sort()

print(sorted)
print()
print(unsorted)
print()
#2 in place sorting
print("in-place sorting")
unsorted.sort()
print(unsorted)

Sorted
[-1.54167276 -1.28599589 -1.25935351 -1.23853319 -0.58735763 -0.27232247
 -0.25089091  0.07336406  0.50497573  1.39158573]

[-1.54167276 -1.28599589 -1.25935351 -1.23853319 -0.58735763 -0.27232247
 -0.25089091  0.07336406  0.50497573  1.39158573]

in-place sorting
[-1.54167276 -1.28599589 -1.25935351 -1.23853319 -0.58735763 -0.27232247
 -0.25089091  0.07336406  0.50497573  1.39158573]


In [135]:
# Reading and wrting text

a = np.arange(0.0,5.0,0.5)
print(a)
np.savetxt('test.txt', a, fmt='%1.2f')

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [138]:
#loading the saved file
a2 = np.loadtxt ('test.txt')
a2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [143]:
#string data
a = np.array(['one', 'two','three'])
print(a)
#save
np.savetxt('test2.txt', a, fmt='%s')
#read
#np.loadtxt('test2.txt', dtype = 'str')
#or
a2 = np.genfromtxt('test2.txt',dtype='str')
a2


['one' 'two' 'three']


array(['one', 'two', 'three'], dtype='<U5')

In [150]:
#comma delimted

a = np.array([[1,2,3],[4,5,6],[7,8,8]])
print(a)
np.savetxt('test3.csv',a, delimiter = ',', fmt ='%d')

#read
a2 = np.loadtxt('test3.csv', dtype = 'int', delimiter =',')
a2


[[1 2 3]
 [4 5 6]
 [7 8 8]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])

In [160]:
tst1 = np.loadtxt('months.txt',dtype = 'str')
print(tst1)
type(tst1)


['Jan' 'Feb' 'Mar' 'Apr' 'May' 'June' 'July' 'Aug' 'Sept' 'Oct' 'Nov'
 'Dec']


numpy.ndarray

In [169]:
tst2 = np.loadtxt('avg-monthly-precip.txt')
print(tst2)
type(tst2)
print(tst2.mean(axis=0))
print(tst2.min())
print(tst2.max())
print(np.std(tst2))
print(np.median(tst2))

[0.7  0.75 1.85 2.93 3.05 2.02 1.93 1.62 1.84 1.31 1.39 0.84]
1.6858333333333333
0.7
3.05
0.7318408107110604
1.73
